### ISSUE TITLE
Use first server template if requested node label is empty/null

### ISSUE THREAD

**Issue by jwwk** [jenkinsci/hetzner-cloud-plugin#12]
### Feature Request

I propose matching the first server template when there isn't an explicitly requested node label. This is more in line with other implementations, such as the [Docker Plugin](https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L566-L568) or the [EC2 Plugin](https://github.com/jenkinsci/ec2-plugin/blob/master/src/main/java/hudson/plugins/ec2/EC2Cloud.java#L388-L391).
Currently, an [empty list is returned](https://github.com/jenkinsci/hetzner-cloud-plugin/blob/main/src/main/java/cloud/dnation/jenkins/plugins/hetzner/HetznerCloud.java#L160-L162) if the label is empty.

Also, I had difficulties understanding the context of "Label" in this form:
<img src="https://user-images.githubusercontent.com/6892510/146195894-bb6b2251-43b8-4c93-9ed6-9662cc96144e.png" width="300">
I needed to look up the code in this repo to find out that this is referring to `hudson.model.Label` and not to the labels at Hetzner Cloud. Maybe it would be possible to add another field for assigning Hetzner Cloud labels.

Besides these initial difficulties, the plugin works fine 🎉  Thanks for your effort!

**Comment by rkosegi** [comment]
First of all, thank you for bug report.

> I propose matching the first server template when there isn't an explicitly requested node label. This is more in line with other implementations, such as the Docker Plugin or the EC2 Plugin.
> Currently, an empty list is returned if the label is empty.

This is actually result of decision to treat every new agent node to be used in [Exclusive](https://javadoc.jenkins.io/hudson/model/Node.Mode.html#EXCLUSIVE) mode, which essentially means that it can execute only job with exact same label.

We can add configuration option so it will have similar behavior as you are proposing.

> Also, I had difficulties understanding the context of "Label" in this form

That's something that is used commonly used in different plugins as well, for example in [Docker Plugin](https://github.com/jenkinsci/docker-plugin/blob/master/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/help-labelString.html) that you mentioned.
I will make wording more clear in help.

> Maybe it would be possible to add another field for assigning Hetzner Cloud labels.

I'm not strongly against placing arbitrary labels on Hetzner nodes, but I don't see what benefit it would have.
Also plugin itself [places](https://github.com/jenkinsci/hetzner-cloud-plugin/blob/main/src/main/java/cloud/dnation/jenkins/plugins/hetzner/HetznerCloudResourceManager.java#L51) some [specific labels](https://github.com/jenkinsci/hetzner-cloud-plugin/blob/main/src/main/java/cloud/dnation/jenkins/plugins/hetzner/HetznerConstants.java#L59) used for identification.
If user interferes with these labels, it could disrupt ability for plugin to clean node instances.

**Comment by rkosegi** [comment]
@jwwk you should now be able to configure `mode` in template setting as `Use this node as much as possible`. If you don't provide any labels, provisioned node should be able to handle any job. Please let us know in case of issues.
