### ISSUE TITLE
Connect to a Public IP instead of Private IP

### ISSUE THREAD

**Issue by phaniops** [jenkinsci/hetzner-cloud-plugin#14]
### What feature do you want to see added?

I have my Jenkins master on AWS. It is able to launch slave on Hetzner but unable to connect as it tried to connect with Hetzner Private IP.

Any Solution?

**Comment by rkosegi** [comment]
By default, there is no private IP in Hetzner cloud, unless you explicitly configure private network.

See this for more details https://github.com/jenkinsci/hetzner-cloud-plugin/issues/7

**Comment by phaniops** [comment]
Thank you very much. That worked
