### ISSUE TITLE
Support of private+public ip's 

### ISSUE THREAD

**Issue by eugen-korentsov** [jenkinsci/hetzner-cloud-plugin#44]
### What feature do you want to see added?

Hi,
I want to use jenkins-slaves with an internal network ( because I have caching docker registry proxy, in the same network in Hetzner), but Jenkins master is outside of Hetzner datacenter, so is it possible to connect to public IP, but still attach the newly created server to the internal network?

**Comment by rkosegi** [comment]
Hi, [current logic](https://github.com/jenkinsci/hetzner-cloud-plugin/blob/9923ba9f47a5dcda340b18b7eea6134699be5457/src/main/java/cloud/dnation/jenkins/plugins/hetzner/launcher/HetznerServerComputerLauncher.java#L151) does not allow this kind of topology:
```java
            if (serverDetail.getPrivateNet() != null && !serverDetail.getPrivateNet().isEmpty()) {
                ipv4 = serverDetail.getPrivateNet().get(0).getIp();
            } else {
                ipv4 = serverDetail.getPublicNet().getIpv4().getIp();
            }
```
which means that if you are attached to private network, there is no way to connect to agents via public IP.

This shouldn't be too difficult to implement ;)

**Comment by eugen-korentsov** [comment]
I will be very grateful if you implement it, thanks.
