### ISSUE TITLE
Feature to use only private network

### ISSUE THREAD

**Issue by ludmata** [jenkinsci/hetzner-cloud-plugin#51]
### What feature do you want to see added?

In Hetzner cloud is possible to create a virtual machine using only private network (no public IP address). 
According to documentation:
Network - Network ID (integer) or label expression that resolves into single network. When specified, private IP address will be used instead of public, so Jenkins controller must be part of same network (or have other means) to communicate with newly created server
So, I hoped that will prevent creating a public network, but it seems I have misunderstood it. Now I have hacked my way to use the private network as default gateway, but it will be nice if there is a feature in the plugin to just disable using public network.

**Comment by rkosegi** [comment]
Hi, thanks for an idea.
This shouldn't be difficult to be implemented.
