### ISSUE TITLE
Support Hetzner Cloud networks in server templates

### ISSUE THREAD

**Issue by sandrinr** [jenkinsci/hetzner-cloud-plugin#7]
### Dependencies

None that I would be aware of.

### Feature Request

Support Hetzner Cloud networks in server templates.

Jenkins nodes regularly need to access resources on private networks. Hetzner provides means to attach cloud components to private networks. These networks are attached on a per server basis.

The Jenkins Hetzner Cloud plugin creates servers according to templates. Allowing to configure to which networks the server shall connect would allow simple and elegant solutions to access private resources.

**Comment by rkosegi** [comment]
To implement this enhancement, following tasks has to be done:

- [ ] Extend API client with network related calls
- [ ] Add configuration option for user to choose network
- [ ] Update documentation with examples

**Comment by rkosegi** [comment]
You can now specify either network ID or label expression that resolves to single network in server template. See README for more details.

**Comment by sandrinr** [comment]
That was quick! Thanks :-)!
