### ISSUE TITLE
Support attaching volumes to a server

### ISSUE THREAD

**Issue by marvinruder** [jenkinsci/hetzner-cloud-plugin#71]
### What feature do you want to see added?

Persisting caches beyond the lifetime of a cloud agent may significantly improve performance of builds directly after provisioning. This can be achieved by using Hetzner’s Block Storage Volumes. They are accessible both via REST API (while [creating a server](https://docs.hetzner.cloud/#servers-create-a-server) and [as a separate endpoint](https://docs.hetzner.cloud/#volume-actions-attach-volume-to-a-server)) and CLI.

A possible implementation would look like this:

- It is possible to add a list of pre-existing volumes to a server template.
- A volume is identified by its ID that can be entered into a text field.
- A volume’s name can be resolved via a “Verify volume” button.
- The automount option can be configured using one checkbox for all volumes.
- A descriptive text
  - explains that for automount to work the volume must exist and be formatted already,
  - explains that the Instance Cap must be set to 1 when working with volumes, since volumes cannot be attached to multiple servers at the same time
  - provides information regarding the default mount point (`/mnt/HC_Volume_${id}`) as well as the device in the file system (`/dev/disk/by-id/scsi-0HC_Volume_${id}`)
- An array of volume IDs and the boolean automount parameter are added to the server creation API call

### Upstream changes

The [Java Hetzner Cloud Client](https://github.com/dNationCloud/hetzner-cloud-client-java) would likely need to be extended.

**Comment by rkosegi** [comment]
Hi @marvinruder, thank you for feature request.
If implemented this way, you can effectively provision just single VM, right? (you can't attach volume to multiple servers at once)
It shouldn't be too hard to implement it though.

**Comment by marvinruder** [comment]
> If implemented this way, you can effectively provision just single VM, right? (you can't attach volume to multiple servers at once)

Yes, that is correct, I updated the description above to include that.

**Comment by rkosegi** [comment]
@marvinruder [new release](https://github.com/jenkinsci/hetzner-cloud-plugin/releases/tag/82.ve3d68a85fd22) should support this feature.

**Comment by marvinruder** [comment]
Thanks, works as expected!
