### ISSUE TITLE
FR: Ability to connect directly via IPv6

### ISSUE THREAD

**Issue by samip5** [jenkinsci/hetzner-cloud-plugin#77]
### What feature do you want to see added?

I would like to see the ability to connect via IPv6, as IPv4 addresses cost extra.

**Comment by rkosegi** [comment]
Hi @samip5, 
thank you for raising this feature request.

Since I'm lacking native IPv6 coverage locally, I'm not sure I can help to implement this.
PR is always welcome.

**Comment by samip5** [comment]
> Hi @samip5, 
> 
> thank you for raising this feature request.
> 
> 
> 
> Since I'm lacking native IPv6 coverage locally, I'm not sure I can help to implement this.
> 
> PR is always welcome.

You could probably use a tunnel for it from eg Hurricane Electric.

Could you share some light into how does the plugin decide if it can connect via v4?

**Comment by rkosegi** [comment]
Hi @samip5, I have some doubts, but you should be able to force plugin to use IPv6 by choosing connection method `Connect using public IPv6 address only`.

It takes IPv6 as-is from Hetzner API and use it to establish SSH connection.

Would you be able to test it out? If so, I can provide a HPI file

**Comment by samip5** [comment]
@rkosegi I should be able to test it, so please provide the hpi file.

**Comment by samip5** [comment]
> It takes IPv6 as-is from Hetzner API and use it to establish SSH connection.

You shouldn't take it as is. It's in a prefix notation, and the instance is reacheable at ::1 of the /64 prefix.

Eg it's usually like `::/64` but the correct address would end in `::1`

**Comment by rkosegi** [comment]
Hi, @samip5 see attached [hetzner-cloud.zip](https://github.com/jenkinsci/hetzner-cloud-plugin/files/15141119/hetzner-cloud.zip) with HPI inside

It's the same thing (but zipped) if you build it yourself using `mvn clean install` on branch `feature/ipv6-support`. To install HPI file, just follow instructions in [README](https://github.com/jenkinsci/hetzner-cloud-plugin?tab=readme-ov-file#installation-from-source)

**Comment by samip5** [comment]
> It's the same thing (but zipped) if you build it yourself using `mvn clean install` on branch `feature/ipv6-support`.

I did actually try, but maven was quite unhappy, so it did not manage to even try to build it. :)

**Comment by rkosegi** [comment]
> > It's the same thing (but zipped) if you build it yourself using `mvn clean install` on branch `feature/ipv6-support`.
> 
> I did actually try, but maven was quite unhappy, so it did not manage to even try to build it. :)

yeah, it needs some [setup](https://www.jenkins.io/doc/developer/tutorial/prepare/), at least settings.xml should have jenkins' plugin repos

**Comment by samip5** [comment]
It just occurred to me that connecting alone is not enough, as the server needs to be provisioned without IPv4 at all.

**Comment by samip5** [comment]
> Hi, @samip5 see attached [hetzner-cloud.zip](https://github.com/jenkinsci/hetzner-cloud-plugin/files/15141119/hetzner-cloud.zip) with HPI inside
> 
> It's the same thing (but zipped) if you build it yourself using `mvn clean install` on branch `feature/ipv6-support`. To install HPI file, just follow instructions in [README](https://github.com/jenkinsci/hetzner-cloud-plugin?tab=readme-ov-file#installation-from-source)
> 
> Just realized that you can also grab it from Jenkins itself 🙂 https://ci.jenkins.io/job/Plugins/job/hetzner-cloud-plugin/view/change-requests/job/PR-78/

It does work: `2024-04-28 10:35:03.546+0000 [id=3068]	INFO	c.d.j.p.h.Helper$LogAdapter#info: Connected to hcloud-vxxyedwa1wyixnyi via 2a01:4f9:c012:cb4a::1`

But I meant this as connecting via IPv6 aka no IPv4 should be provisioned.

**Comment by rkosegi** [comment]
I made some improvements, build is [here](https://ci.jenkins.io/job/Plugins/job/hetzner-cloud-plugin/view/change-requests/job/PR-78/3/)

Now you can specify connection method that enables IPv6 only (under advanced template options)
![image](https://github.com/jenkinsci/hetzner-cloud-plugin/assets/3736012/97b4cc57-79ae-46ce-9322-01c27a8d468b).

**Comment by samip5** [comment]
Thanks, works as intended even if one would say that building things via IPv6-only is currently troublesome (due to Github and PyPi being unreacheable without NAT64/DNS64) :)

**Comment by samip5** [comment]
Could we also have `Connect using private IPv4 address if available, otherwise using public IPv6 address`?
